name: Generate minified versions

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 
    - name: Update files
      env:
        PYTHONPATH: ${{ github.workspace }}
      shell: python
      run: |
        import versiondb
        list = versiondb.VersionList('.')
        list.save_minified('armeabi-v7a')
        list.save_minified('x86')
        list.save_minified('arm64-v8a')
        list.save_minified('x86_64')
    - name: Update git
      run: |
        # from https://github.com/orgs/community/discussions/26560
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        (git add . && git commit -m "Update minified json's" && git push) || :
